site_name: FaceAPP

site_url: http://127.0.0.1:8000
repo_name: JakubKacerek/BP_TUL_25
repo_url: https://github.com/JakubKacerek/BP_TUL_25
edit_uri: https://github.com/JakubKacerek/BP-DOCS/tree/main/docs/

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details


theme:
  name: material
  language: cs
  palette:
      - media: "(prefers-color-scheme)"
        toggle:
            icon: material/brightness-auto
            name: Switch to light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: black
        accent: black
        toggle:
            icon: material/brightness-7
            name: Switch to dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: black
        accent: blue
        toggle:
            icon: material/brightness-4
            name: Switch to system preference
  features:
    - navigation.footer
    - navigation.instant
    - content.action.edit
    - search.suggest
    - search.share
    - content.code.copy
    - content.code.select
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes


nav:
  - "Domů":
    - index.md
  - "Dashboard":
    - dashboard/index.md
    - "Předpoklady":
      - dashboard/předpoklady/index.md
    - "Instalace":
      - dashboard/instalace/index.md
    - "Použití":
      - dashboard/použití/index.md
  - "Více":
    - more/Vývoj.md